### ISSUE TITLE
Connecting two metadata tables

### ISSUE THREAD

**Issue by tungwinxp** [flu-crew/dairy-cattle-hpai-experiment#1]
Hi, thanks for the insights from this study. I'm wondering whether you have the metadata link between clinical-challenge-study-data.xlsx and the sequencing mutational metadata (which cow, dpi, Ct value, tissue, inoculation route, etc.).

**Comment by tkanderson** [comment]
Hi @tungwinxp could you please email me at tavis.anderson@usda.gov and I can email the link. I will revise and upload the key later this week (that will cascade across to the zenodo release too).

**Comment by tkanderson** [comment]
@tungwinxp I've updated the repo to include a spreadsheet that has the information requested (minus inoculation route - though this is in the clinical challenge study data spreadsheet). If you have any questions, please reopen this issue and I can address it.
